language: csharp
solution: DesignPatterns.sln
install:
    - nuget install NUnit.ConsoleRunner -OutputDirectory testrunner
    - nuget restore DesignPatterns.sln
script:
    - msbuild /p:Configuration=Release DesignPatterns.sln
    - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Tests/bin/Release/netcoreapp2.0/Tests.dll
