language: csharp
dotnet: 2.0.0
solution: DesignPatterns.sln
install:
    - nuget install NUnit.ConsoleRunner -OutputDirectory testutils
    - nuget install OpenCover -OutputDirectory testutils
    - dotnet restore DesignPatterns.sln
script:
    - msbuild /p:Configuration=Release DesignPatterns.sln
    - mono ./testutils/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Tests/bin/Release/net462/Tests.dll
    - mono ./testutils/OpenCover*/tools/OpenCover.Console.exe -register:user -target:./scripts/tests.sh -searchdirs:../Tests/bin/Debug/net462 -output:coveragereport.xml
cache:
    - .nuget/packages
