language: csharp
dotnet: 2.0.0
solution: DesignPatterns.sln
install:
    - nuget install NUnit.ConsoleRunner -OutputDirectory testutils
    - dotnet restore DesignPatterns.sln
script:
    - msbuild /p:Configuration=Release DesignPatterns.sln
    - mono ./testutils/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Tests/bin/Release/net462/Tests.dll
cache:
    - .nuget/packages
